# Generated by Django 3.2.4 on 2022-06-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productstemplate', '0002_delete_extenduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.ImageField(default='', upload_to='Product Images'),
            preserve_default=False,
        ),
    ]
