# Generated by Django 3.2.4 on 2022-06-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productstemplate', '0003_category_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.ImageField(upload_to='Category'),
        ),
    ]
