# Generated by Django 3.2.4 on 2022-06-24 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productstemplate', '0008_auto_20220623_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datatime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, upload_to='Product Images'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='datatime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(help_text='Add Product Model Name or Product Name.', max_length=50),
        ),
    ]
