# Generated by Django 3.2.4 on 2022-07-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productstemplate', '0010_auto_20220714_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
    ]
