# Generated by Django 3.2.4 on 2022-07-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productstemplate', '0012_order_sub_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='lastdatatime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
