# Generated by Django 3.2.4 on 2022-07-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productstemplate', '0014_alter_wishlist_lastdatatime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='lastdatatime',
        ),
    ]
