# Generated by Django 3.2.4 on 2022-07-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productstemplate', '0017_auto_20220721_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headlinemessage',
            name='logo',
            field=models.ImageField(help_text='Upload the Home pages Cover image or Any Message', upload_to='HeadLine', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='headlinemessage',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Imagen name or any Messages', max_length=255),
        ),
    ]
