# Generated by Django 4.0.4 on 2022-06-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='picture',
            field=models.ImageField(upload_to='userImages/'),
        ),
    ]
